import type { Metadata } from "next";
import { Bodoni_Moda, Crimson_Pro, JetBrains_Mono, Newsreader } from "next/font/google";
import "./globals.css";

const SITE_URL = "https://conclave-ai.dev";

// Judicial-conclave typography stack:
//   - Bodoni Moda: high-contrast didone display. Aggressive at large
//     sizes, classical at small. Optical-size axis makes h1 and
//     section heads share the same family.
//   - Crimson Pro: modulated old-style serif body. Designed for
//     long-form reading; carries the editorial-broadsheet metaphor.
//   - Newsreader Italic: secondary italic voice — used for pulled
//     quotes and emphasis where Crimson italic would be too uniform.
//   - JetBrains Mono: kept for cli, version markers, numerics.
const fontDisplay = Bodoni_Moda({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-display",
  weight: ["400", "500", "700", "800", "900"],
});

const fontBody = Crimson_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-serif-body",
  weight: ["300", "400", "500", "600", "700"],
});

const fontItalic = Newsreader({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-italic",
  style: ["italic"],
  weight: ["400", "500", "600"],
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Conclave AI — multi-agent code review for your PRs",
  description:
    "A council of AI agents reviews every PR against your PRD. Verdict and dissent on every commit.",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
  },
  openGraph: {
    title: "Conclave AI",
    description:
      "A council of AI agents reviews every PR against your PRD. Verdict and dissent on every commit.",
    type: "website",
    url: SITE_URL,
    siteName: "Conclave AI",
    // 1200×630 OG image is auto-generated by app/opengraph-image.tsx
    // (Next.js file-based metadata convention — the file's default
    // export is rendered to PNG at request time and served as
    // /opengraph-image.{hash}.png with cache headers).
  },
  twitter: {
    card: "summary_large_image",
    title: "Conclave AI",
    description:
      "A council of AI agents reviews every PR against your PRD.",
  },
  alternates: {
    canonical: SITE_URL,
  },
};

// JSON-LD structured data — gives Google enough context to surface the
// landing as a SoftwareApplication rich result (category, free / paid
// offers, screenshot of the OG image as productImage). Stamped inline
// in the <head> via a regular Script component below.
const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "Conclave AI",
  applicationCategory: "DeveloperApplication",
  applicationSubCategory: "Code review",
  operatingSystem: "Web · CLI (Node ≥ 20) · GitHub App",
  description:
    "A council of three frontier AI agents (Claude, GPT-5, Gemini) reviews every PR independently, then deliberates against your PRD to surface spec mismatches a single model misses.",
  url: SITE_URL,
  image: `${SITE_URL}/opengraph-image`,
  // v0.14.5 — keep only the free tier in structured data so Google's
  // SoftwareApplication rich-result surfaces "Free" not the paid tiers.
  // Pricing is still on the landing page; we just don't broadcast the
  // dollar figures into search snippets while pricing is in beta and
  // may change.
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    description: "Free with bring-your-own Anthropic API key. Open beta.",
  },
  publisher: {
    "@type": "Organization",
    name: "3SVS",
    url: "https://www.3svs.com",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${fontDisplay.variable} ${fontBody.variable} ${fontItalic.variable} ${fontMono.variable}`}
    >
      <head>
        {/* JSON-LD structured data for SoftwareApplication rich results.
            Stamped here (head) so crawlers see it on first parse. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
        />
      </head>
      <body className="antialiased font-sans bg-parchment text-ink">{children}</body>
    </html>
  );
}
